name: Danger CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Danger
    steps:
      # TCHAP use github app token
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID_DANGERBOT }}
          private_key: ${{ secrets.APP_PEM_DANGERBOT }}
      - uses: actions/checkout@v4
      - run: |
          npm install --save-dev @babel/plugin-transform-flow-strip-types
      - name: Danger
        uses: danger/danger-js@11.2.6
        with:
          args: "--dangerfile ./tools/danger/dangerfile.js"
        env:
          DANGER_GITHUB_API_TOKEN: ${{ steps.generate_token.outputs.token }}
